// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaMVaMduBjI-m3A2-k1Mt1eKWgJfhk5JI',
    appId: '1:1091841941233:web:ba73e5e4b91bd9db291350',
    messagingSenderId: '1091841941233',
    projectId: 'sesac-hangco',
    authDomain: 'sesac-hangco.firebaseapp.com',
    storageBucket: 'sesac-hangco.appspot.com',
    measurementId: 'G-TB5KFTTSEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-gfWjYYXD7UvzJQbBZApgYaMSZvM8bwg',
    appId: '1:1091841941233:android:2b44f1b1a76c04af291350',
    messagingSenderId: '1091841941233',
    projectId: 'sesac-hangco',
    storageBucket: 'sesac-hangco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzdj73cNRT-et3Q69k-nv4c_JxEsRF8Zs',
    appId: '1:1091841941233:ios:5b168ade241939b1291350',
    messagingSenderId: '1091841941233',
    projectId: 'sesac-hangco',
    storageBucket: 'sesac-hangco.appspot.com',
    iosBundleId: 'com.example.moments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzdj73cNRT-et3Q69k-nv4c_JxEsRF8Zs',
    appId: '1:1091841941233:ios:5b168ade241939b1291350',
    messagingSenderId: '1091841941233',
    projectId: 'sesac-hangco',
    storageBucket: 'sesac-hangco.appspot.com',
    iosBundleId: 'com.example.moments',
  );
}
